# Generated by Django 4.2.5 on 2023-09-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('calories', models.FloatField(verbose_name='Калорийность на 100г')),
            ],
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Описание рецепта')),
                ('text', models.TextField(verbose_name='Текст рецепта')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Описание подписки')),
                ('expire_date', models.DateField(verbose_name='Дата окончания подписки')),
                ('have_breakfast', models.BooleanField(default=False, verbose_name='Завтраки')),
                ('have_dinner', models.BooleanField(default=False, verbose_name='Обеды')),
                ('have_supper', models.BooleanField(default=False, verbose_name='Ужины')),
                ('have_dessert', models.BooleanField(default=False, verbose_name='Десерты')),
                ('number_of_persons', models.PositiveIntegerField(default=1, verbose_name='Кол-во персон')),
                ('allergies', models.ManyToManyField(related_name='banned_for_subscriptions', to='plan.ingredient', verbose_name='Ингредиенты с аллергией')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plan.menutype')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=100, verbose_name='Кол-во (в граммах).')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='plan.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='plan.recipe', verbose_name='В рецепте')),
            ],
        ),
    ]
