# Generated by Django 4.2.5 on 2023-09-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientitem',
            options={'verbose_name': 'Ингредиент в заказе', 'verbose_name_plural': 'Ингредиенты в заказе'},
        ),
        migrations.AlterModelOptions(
            name='menutype',
            options={'verbose_name': 'Тип меню', 'verbose_name_plural': 'Типы меню'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
