# Generated by Django 4.2.5 on 2023-09-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='recipes/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='plan.menutype', verbose_name='Тип меню'),
            preserve_default=False,
        ),
    ]
