# Generated by Django 4.2.5 on 2023-09-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_startrecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startrecipe',
            name='recipe',
        ),
        migrations.AddField(
            model_name='startrecipe',
            name='recipe',
            field=models.ManyToManyField(blank=True, related_name='start_recipes', to='plan.recipe', verbose_name='Рецепт'),
        ),
    ]
