# Generated by Django 4.2.5 on 2023-09-28 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0005_remove_startrecipe_recipe_startrecipe_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_acive',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='banned_for_subscriptions', to='plan.ingredient', verbose_name='Ингредиенты с аллергией'),
        ),
    ]
