# Generated by Django 4.2.5 on 2023-09-28 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_subscription_is_acive_subscription_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала подписки'),
        ),
    ]
