# Generated by Django 4.2.5 on 2023-10-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_categoryingredient_alter_ingredient_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutype',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_menu', to='plan.menutype'),
        ),
    ]
