# Generated by Django 4.2.5 on 2023-10-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_menutype_slug_subscription_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='banned_for_subscriptions', to='plan.categoryingredient', verbose_name='Ингредиенты с аллергией'),
        ),
    ]
