# Generated by Django 4.2.5 on 2023-10-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_alter_subscription_allergies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='menu',
        ),
    ]
